### ISSUE TITLE
debug code

### ISSUE THREAD

**Issue by ccraddock** [dclark87/afni#2]
remember to remove DEBUG code such as this:

https://github.com/dclark87/afni/blob/master/src/3dECM.c#L499-L515

**Comment by dclark87** [comment]
I believe I cleaned out all of the DEBUG code I added.

**Comment by ccraddock** [comment]
FWIW, if you believe that the debug code could be useful in the future you
can either add a runtime flag to enable it (i.e. wrap with if (debug ==
TRUE) ) or you could make it a compile time flag (#if DEBUG) rather than
deleting.

-cc


On Tue, Mar 29, 2016 at 7:18 PM, Daniel Clark <notifications@github.com>
wrote:

> Closed #2 <https://github.com/dclark87/afni/issues/2>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/dclark87/afni/issues/2#event-607426141>
>



-- 
Director of Imaging, Center for the Developing Brain, Child Mind Institute
<http://childmind.org>
Director, Computational NeuroImaging Lab
<http://computational-neuroimaging-lab.org/>, Nathan S. Kline Institute for
Psychiatric Research <http://www.rfmh.org/nki/>
Co-Founder, The Neuro Bureau <http://neurobureau.org>
Impact Story <https://impactstory.org/CameronCraddock>
Google Scholar Citations
<http://scholar.google.com/citations?user=lZ9hwSsAAAAJ&hl=en>
GitHub <https://github.com/ccraddock>

Share that Brain @ the International Neuroimaging Datasharing Initiative
<http://fcon_1000.projects.nitrc.org/>!
The GigaScience Brainhack Thematic Series
<http://brainhack.org/brainhack-thematic-series-call-for-papers/> is open
for your submission.
Submit a paper to the Neuroimage Special Issue on Brain Segmentation and
Parcellation
<http://www.journals.elsevier.com/neuroimage/call-for-papers/brain-segmentation-and-parcellation/>
!

Join me at upcoming Brainhack <http://brainhack.org> Events:
2016.06.26 - 2016.06.30 OHBM Hackathon
<http://brainhack.org/ohbm-hackathon-2016/>, Lausanne, Switzerland
2016.09.18 - 2016.09.20 Brainhack Vienna <http://restingstate.net>, Vienna,
Austria
