### ISSUE TITLE
Use C-style comments (/* */)

### ISSUE THREAD

**Issue by ccraddock** [dclark87/afni#3]
using C++ style comments in C code is bad form (i may have done so too, but its still bad ;)).
//
//        if( do_binary == 1 )
//        {
//            sprintf(str,"Binary ECM");
//        }
//        else
//        {
//            sprintf(str,"Weighted ECM");
//        }

**Comment by dclark87** [comment]
Just read up on why using C++ comments in C code can be harmful, and not fully backwards compatible. This is remedied now.
